<?php

namespace App\Classes;

use App\Classes\Conta;

class ContaCorrente extends Conta
{
    private $taxaSaque;

    public function __construct(int $taxaSaque = 12)
    {
        $this->taxaSaque = $taxaSaque;
    }

    public function efetuarSaque()
    {
        parent::efetuarSaque(); // TODO: Change the autogenerated stub
    }

    public function setTaxaSaque($taxaSaque)
    {
        return $this->taxaSaque = $taxaSaque;
    }

    public function getTaxaSaque()
    {
        return $this->taxaSaque;
    }
}

?>