<?php

namespace App\Classes;

class ContaPoupanca extends Conta
{
    private $taxaDeposito;

    public function __construct(int $taxaDeposito = 6)
    {
        $this->taxaDeposito = $taxaDeposito;
    }

    public function efetuarDeposito()
    {
        parent::efetuarDeposito(); // TODO: Change the autogenerated stub
    }

    public function setTaxaDeposito($taxadeposito)
    {
        return $this->taxaDeposito = $taxadeposito;
    }

    public function getTaxaDeposito()
    {
        return $this->taxaDeposito;
    }
}

?>